name: "Update Pull Request"
on: pull_request

jobs:
  pr_update_text:
    runs-on: ubuntu-latest
    steps:
      - uses: tzkhan/pr-update-action@v1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          branch-regex: '.*\/?gh-\d+'
          lowercase-branch: true
          title-template: '[%branch%]'
          title-prefix-space: true
          uppercase-title: true
          body-template: '[Link to branch: %branch%](https://github.com/gruutak/gruutbot/tree/%branch%)'
          body-prefix-newline-count: 2
          uppercase-body: false